### PR TITLE
Add 4.3.3 docs

### PR DESCRIPTION
**Pull request by LeeLenaleee**
Not 100% sure if it will work, locally I get a white screen with a black bar inside of it, but I also get that for older versions.

Ran the build command and copied the files over and replaced the VERSION placeholder with 4.3.3

### CODE REVIEW

**Review by etimberg — APPROVED** [review]

**Comment by LeeLenaleee** [comment]
I don't have merge rights so you will need to do that :)

**Comment by LeeLenaleee** [comment]
Looks like something did not entirely go wright, will give it a look tonight

**Comment by etimberg** [comment]
I see them here https://www.chartjs.org/docs/4.3.3/

**Comment by etimberg** [comment]
I see, the docs actually get copied in twice. Once to the actual version and once to the `latest` folder. They are built slightly differently each time. 

https://github.com/chartjs/Chart.js/blob/master/.github/workflows/release.yml#L53 this runs the `latest` and https://github.com/chartjs/Chart.js/blob/master/.github/workflows/release.yml#L92 runs the explicit version

**Comment by LeeLenaleee** [comment]
Yeah but the 4.3.3 docs dont have a search icon in the search bar, and the navigation does not work

**Pull request merged**
